engines:
    phpcodesniffer:
        enabled: true
        config:
            ignore_warnings: true
    phpmd:
        enabled: true
        config:
            file_extensions: "php"
            rulesets: "unusedcode,codesize,naming,cleancode,design"
    duplication:
        enabled: true
        config:
            languages:
            - php


ratings:
    paths:
        - "lib/*.php"

exclude_paths:
- "modules/*"
- "tests/*"
- "third_party/*"
- "docs/*"
- "language/*"
- "website/*"
