language: php

php:
  - 7.0
  - hhvm

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration tests/phpunit/phpunit.xml

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#hastymail"
