language: php

php:
    - 5.6

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: cd tests/phpunit && phpunit

env:
    - DB=mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root -e 'create table hm_user (username varchar(255), hash varchar(255), primary key (username));' test
  - mysql -u root -e 'create table hm_user_session (hm_id varchar(255), data longblob, date timestamp, primary key (hm_id));' test
  - mysql -u root -e 'create table hm_user_settings( username varchar(255), settings longblob, primary key (username));' test
  - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY '123456';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost';"

# configure notifications (email, IRC, campfire etc)
notifications:
    irc: "irc.freenode.org#hastymail"
