language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'

# run the phpunit tests, then the selenium tests
script: cd tests/phpunit && /usr/local/bin/phpunit && cd ../selenium && sh ./runall.sh

# the unit tests need a DB setup, the selenium tests do not. Eventually
# we should test postgresql and sqlite in addition to mysql
env:
    - DB=mysql

# set up everything we need. The unit tests only require the last section.
# Everything else is for the selenium tests
before_install:

    # install and configure everything
    - sh .travis/setup.sh

# dump some useful info to the logs
after_script:
    - sudo cat /var/log/apache2/error.log
    - sudo cat /var/log/mail.err

# use sauce labs for the selenium tests
addons:
    sauce_connect:
        username: "sail_frog"
        access_key: "d0f2e9da-5bea-48b3-bf3d-734b15027afe"

# send notices to our irc channel
notifications:
    irc: "irc.freenode.org#hastymail"
