language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'

# run the phpunit tests, then the selenium tests
script: cd tests/phpunit && /usr/local/bin/phpunit && cd ../selenium && sh ./runall.sh

# the unit tests need a DB setup, the selenium tests do not. Eventually
# we should test postgresql and sqlite in addition to mysql
env:
    - DB=mysql

# set up everything we need. The unit tests only require the last section.
# Everything else is for the selenium tests
before_install:

    # PHP7+ needs ldap configured
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then echo 'extension=ldap.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then echo 'extension=ldap.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

    # add a system user we will log into Cypht with
    - sudo useradd -m -d /home/testuser -p '$1$Ud5O7hjy$w9hqt3c2jpN2bvztgTWb11' testuser

    # update apt repo
    - sudo apt-get -qq update

    # setup dovecot for IMAP
    - sudo apt-get install -y dovecot-imapd
    - sudo sleep 10
    - sudo stop dovecot
    - echo "mail_location = maildir:/home/%u/Maildir" | sudo tee --append /etc/dovecot/conf.d/10-mail.conf
    - sudo start dovecot

    # setup Cypht. Use different browsers for each version of PHP being tested
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then wget https://cypht.org/travis/creds.py-ff -O creds.py; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then wget https://cypht.org/travis/creds.py-ie -O creds.py; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then wget https://cypht.org/travis/creds.py-edge -O creds.py; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then wget https://cypht.org/travis/creds.py-chrome -O creds.py; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then wget https://cypht.org/travis/creds.py-safari -O creds.py; fi
    - wget https://cypht.org/travis/hm3.ini
    - mv creds.py tests/selenium/
    - php ./scripts/config_gen.php

    # get old stable version of phpunit
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.4" ]]; then wget https://phar.phpunit.de/phpunit-4.8.phar -O phpunit; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then wget https://phar.phpunit.de/phpunit-4.8.phar -O phpunit; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then wget https://phar.phpunit.de/phpunit-5.7.phar -O phpunit; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then wget https://phar.phpunit.de/phpunit-5.7.phar -O phpunit; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then wget https://phar.phpunit.de/phpunit-5.7.phar -O phpunit; fi
    - chmod +x phpunit
    - sudo mv phpunit /usr/local/bin/phpunit

    # setup apache and fpm
    - wget https://cypht.org/travis/www.conf
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    - sudo apt-get install python-pip
    - sudo pip install selenium
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then sudo cp www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then sudo cp www.conf ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/; fi
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - wget https://cypht.org/travis/apache.conf -O travis-ci-apache
    - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart

    # setup env for unit tests
    - mysql -u root -e 'create database if not exists test;'
    - mysql -u root -e 'create table hm_user (username varchar(255), hash varchar(255), primary key (username));' test
    - mysql -u root -e 'create table hm_user_session (hm_id varchar(255), data longblob, date timestamp, primary key (hm_id));' test
    - mysql -u root -e 'create table hm_user_settings( username varchar(255), settings longblob, primary key (username));' test
    - mysql -u root -e "create user 'test'@'localhost' identified by '123456';"
    - mysql -u root -e "grant all privileges on test.* to 'test'@'localhost';"
    - mysql -u root -e "insert into hm_user values('unittestuser', 'sha512:86000:xfEgf7NIUQ2XkeU5tnIcA+HsN8pUllMVdzpJxCSwmbsZAE8Hze3Zs+MeIqepwocYteJ92vhq7pjOfrVThg/p1voELkDdPenU8i2PgG9UTI0IJTGhMN7rsUILgT6XlMAKLp/u2OD13sukUFcQNTdZNFqMsuTVTYw/Me2tAnFwgO4=:rfyUhYsWBCknx6EmbeswN0fy0hAC0N3puXzwWyDRquA=');" test
    - mysql -u root -e "insert into hm_user_settings values('testuser', 'sFpVPU/hPvmfeiEKUBs4w1EizmbW/Ze2BALZf6kdJrIU3KVZrsqIhKaWTNNFRm3p51ssRAH2mpbxBMhsdpOAqIZMXFHjLttRu9t5WZWOkN7qwEh2LRq6imbkMkfqXg//K294QDLyWjE0Lsc/HSGqnguBF0YUVLVmWmdeqq7/OrXUo4HNbU88i4s2gkukKobJA2hjcOEq/rLOXr3t4LnLlcISnUbt4ptalSbeRrOnx4ehZV8hweQf1E+ID7s/a+8HHx1Qo713JDzReoLEKUsxRQ==');" test
    - echo '+2IdQejfHu4FNYOA3tm0DJVQNg92gcpJf8ETeVj+HK0OU6J5iaV/J823rLm8+5Et7tQLoCCoZwElGTH7N2P2M4JMct1jRyWgjqJQn9FYlovFYj/8fLwkixGo+VMNIKsUwJ42GXTj61nn0Rf4+FO688SfAR5LhaLTXlR6XZ9mJD2/2RX1X+Z1JVl7SrqELgE8wnz5IYCrzqBbgK4MDn86rTtPM9jie3gFS9viMZ7OQRENbXLvwBaIXNLvQlZZn2JBdzXF1spoLnSlq8P0pYXlDig==' > tests/phpunit/data/testuser.txt

# dump some useful info to the logs
after_script:
    - sudo cat /var/log/apache2/error.log
    - sudo cat /var/log/mail.err

# use sauce labs for the selenium tests
addons:
    sauce_connect:
        username: "sail_frog"
        access_key: "d0f2e9da-5bea-48b3-bf3d-734b15027afe"

# send notices to our irc channel
notifications:
    irc: "irc.freenode.org#hastymail"
