language: php

php:
    - 5.6

script: cd tests/phpunit && phpunit

env:
    - DB=mysql

before_install:
  - mysql -u root -e 'create database if not exists test;'
  - mysql -u root -e 'create table hm_user (username varchar(255), hash varchar(255), primary key (username));' test
  - mysql -u root -e 'create table hm_user_session (hm_id varchar(255), data longblob, date timestamp, primary key (hm_id));' test
  - mysql -u root -e 'create table hm_user_settings( username varchar(255), settings longblob, primary key (username));' test
  - mysql -u root -e "create user 'test'@'localhost' identified by '123456';"
  - mysql -u root -e "grant all privileges on test.* to 'test'@'localhost';"
  - mysql -u root -e "insert into hm_user values('unittestuser', 'sha512:86000:xfEgf7NIUQ2XkeU5tnIcA+HsN8pUllMVdzpJxCSwmbsZAE8Hze3Zs+MeIqepwocYteJ92vhq7pjOfrVThg/p1voELkDdPenU8i2PgG9UTI0IJTGhMN7rsUILgT6XlMAKLp/u2OD13sukUFcQNTdZNFqMsuTVTYw/Me2tAnFwgO4=:rfyUhYsWBCknx6EmbeswN0fy0hAC0N3puXzwWyDRquA=');" test
  - mysql -u root -e "insert into hm_user_settings values('testuser', '8moxOokpTk1+tuT0WnwQTsM7AqkWtdMPq7wRtM9sMszuj7IVHZYlvaNa9fJ+VM0DjXnnuFYtmrkOAA5UJ+H0/muOpYgMsaFpQF1k9Urw8WbSaSHPNw==');" test

notifications:
    irc: "irc.freenode.org#hastymail"
