language: php

php:
    - 5.6

script: cd tests/phpunit && phpunit

env:
    - DB=mysql

before_install:
  - mysql -u root -e 'create database if not exists test;'
  - mysql -u root -e 'create table hm_user (username varchar(255), hash varchar(255), primary key (username));' test
  - mysql -u root -e 'create table hm_user_session (hm_id varchar(255), data longblob, date timestamp, primary key (hm_id));' test
  - mysql -u root -e 'create table hm_user_settings( username varchar(255), settings longblob, primary key (username));' test
  - mysql -u root -e "create user 'test'@'localhost' identified by '123456';"
  - mysql -u root -e "grant all privileges on test.* to 'test'@'localhost';"
  - mysql -u root -e "insert into hm_user values('unittestuser', 'sha512:86000:xfEgf7NIUQ2XkeU5tnIcA+HsN8pUllMVdzpJxCSwmbsZAE8Hze3Zs+MeIqepwocYteJ92vhq7pjOfrVThg/p1voELkDdPenU8i2PgG9UTI0IJTGhMN7rsUILgT6XlMAKLp/u2OD13sukUFcQNTdZNFqMsuTVTYw/Me2tAnFwgO4=:rfyUhYsWBCknx6EmbeswN0fy0hAC0N3puXzwWyDRquA=');" test
  - mysql -u root -e "insert into hm_user_settings values('testuser', ' 2t78kjYXcapaBu7V5T3ItpiFTso3h/6N1oTGrZw/mYgJw93THy3hOeIDL9qeEj0It+ocR0GaWVW8g/ugS2b4uzME81YAyuj6PWz5siWO1+jvyiCWWvZssVoUOAcAhyPoAQXnlmn8/DWzCvrs22in2sZbIWu/p+9ll2mc91/tYaUCZEwf50q4E5UgxsQ8RYkUghabfLRElGfIOcMh3XTstmmEiWtDUJLf6waFtSUvpL6FDfM2P7jw5HIfL7+6K9/01AJzJVTP8yJDTLNsM9UM1BV4k9C51YyLjxXIfwboa5I=');" test
  - echo '+2IdQejfHu4FNYOA3tm0DJVQNg92gcpJf8ETeVj+HK0OU6J5iaV/J823rLm8+5Et7tQLoCCoZwElGTH7N2P2M4JMct1jRyWgjqJQn9FYlovFYj/8fLwkixGo+VMNIKsUwJ42GXTj61nn0Rf4+FO688SfAR5LhaLTXlR6XZ9mJD2/2RX1X+Z1JVl7SrqELgE8wnz5IYCrzqBbgK4MDn86rTtPM9jie3gFS9viMZ7OQRENbXLvwBaIXNLvQlZZn2JBdzXF1spoLnSlq8P0pYXlDig==' > tests/phpunit/data/testuser.txt

notifications:
    irc: "irc.freenode.org#hastymail"
