language: php

php:
    - 5.6

#script: cd tests/phpunit && phpunit && cd ../selenium && sh ./runall.sh
script: cd tests/selenium && sh ./runall.sh

env:
    - DB=mysql

before_install:
    - sudo useradd -m -d /home/testuser -p '$1$Ud5O7hjy$w9hqt3c2jpN2bvztgTWb11' testuser
    - sudo apt-get -qq update
    - sudo apt-get install -y dovecot-imapd
    - sudo doveadm reload
    - sudo netstat -lntp
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    - sudo apt-get install python-pip
    - sudo pip install selenium
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    - wget https://cypht.org/travis/apache.conf -O travis-ci-apache
    - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - wget https://cypht.org/travis/hm3.ini
    - wget https://cypht.org/travis/creds.py
    - mv creds.py tests/selenium/
    - php ./scripts/config_gen.php
    - mysql -u root -e 'create database if not exists test;'
    - mysql -u root -e 'create table hm_user (username varchar(255), hash varchar(255), primary key (username));' test
    - mysql -u root -e 'create table hm_user_session (hm_id varchar(255), data longblob, date timestamp, primary key (hm_id));' test
    - mysql -u root -e 'create table hm_user_settings( username varchar(255), settings longblob, primary key (username));' test
    - mysql -u root -e "create user 'test'@'localhost' identified by '123456';"
    - mysql -u root -e "grant all privileges on test.* to 'test'@'localhost';"
    - mysql -u root -e "insert into hm_user values('unittestuser', 'sha512:86000:xfEgf7NIUQ2XkeU5tnIcA+HsN8pUllMVdzpJxCSwmbsZAE8Hze3Zs+MeIqepwocYteJ92vhq7pjOfrVThg/p1voELkDdPenU8i2PgG9UTI0IJTGhMN7rsUILgT6XlMAKLp/u2OD13sukUFcQNTdZNFqMsuTVTYw/Me2tAnFwgO4=:rfyUhYsWBCknx6EmbeswN0fy0hAC0N3puXzwWyDRquA=');" test
    - mysql -u root -e "insert into hm_user_settings values('testuser', 'sFpVPU/hPvmfeiEKUBs4w1EizmbW/Ze2BALZf6kdJrIU3KVZrsqIhKaWTNNFRm3p51ssRAH2mpbxBMhsdpOAqIZMXFHjLttRu9t5WZWOkN7qwEh2LRq6imbkMkfqXg//K294QDLyWjE0Lsc/HSGqnguBF0YUVLVmWmdeqq7/OrXUo4HNbU88i4s2gkukKobJA2hjcOEq/rLOXr3t4LnLlcISnUbt4ptalSbeRrOnx4ehZV8hweQf1E+ID7s/a+8HHx1Qo713JDzReoLEKUsxRQ==');" test
    - echo '+2IdQejfHu4FNYOA3tm0DJVQNg92gcpJf8ETeVj+HK0OU6J5iaV/J823rLm8+5Et7tQLoCCoZwElGTH7N2P2M4JMct1jRyWgjqJQn9FYlovFYj/8fLwkixGo+VMNIKsUwJ42GXTj61nn0Rf4+FO688SfAR5LhaLTXlR6XZ9mJD2/2RX1X+Z1JVl7SrqELgE8wnz5IYCrzqBbgK4MDn86rTtPM9jie3gFS9viMZ7OQRENbXLvwBaIXNLvQlZZn2JBdzXF1spoLnSlq8P0pYXlDig==' > tests/phpunit/data/testuser.txt

addons:
    sauce_connect:
        username: "sail_frog"
        access_key: "d0f2e9da-5bea-48b3-bf3d-734b15027afe"

notifications:
    irc: "irc.freenode.org#hastymail"
